### ISSUE TITLE
请问是否方便公开未处理过的图片数据集？

### ISSUE THREAD

**Issue by RandomTuringDuck** [ytyz1307zzh/CMAC#2]
您项目的*.img是经过ResNET处理过的图片，不知是否方便公开完整的数据集，即包含未处理的图片？非常感谢

**Comment by ytyz1307zzh** [comment]
I am really sorry... 一个是我可能找不到所有的图片了（我当时没经验忽视了保存资源的重要性，实在对不起）…另一个是我没有足够的资源来放这么多图片…确实非常抱歉，如果你确实非常想要原图的话，我这里有原始版的数据集（没有经过train/dev/test划分，图片以url的形式存储），我可以把这个给你…

**Comment by love2poppy** [comment]
那真是太感谢了。原始版也可以的，我自己写个爬虫把图片爬下来就好了。
原始数据集大么，可以发到我的邮箱love2poppy@gmail.com或者您提供一个下载地址，再次感谢。

**Comment by RandomTuringDuck** [comment]
> I am really sorry... 一个是我可能找不到所有的图片了（我当时没经验忽视了保存资源的重要性，实在对不起）…另一个是我没有足够的资源来放这么多图片…确实非常抱歉，如果你确实非常想要原图的话，我这里有原始版的数据集（没有经过train/dev/test划分，图片以url的形式存储），我可以把这个给你…

那真是太感谢了。原始版也可以的，我自己写个爬虫把图片爬下来就好了。
原始数据集大么，可以发到我的邮箱love2poppy@gmail.com或者您提供一个下载地址，再次感谢。

**Comment by ytyz1307zzh** [comment]
原始数据集放在[这里](https://drive.google.com/open?id=1npF-CNpU5AZPnPu6GTE7vvn-SrnBfDRV)，压缩后大概50M的样子。我当时爬图片和处理图片的脚本也在``data``文件夹里，虽然我半年没用过了不过应该能提供一些参考（捂脸

**Comment by RandomTuringDuck** [comment]
> 原始数据集放在[这里](https://drive.google.com/open?id=1npF-CNpU5AZPnPu6GTE7vvn-SrnBfDRV)，压缩后大概50M的样子。我当时爬图片和处理图片的脚本也在`data`文件夹里，虽然我半年没用过了不过应该能提供一些参考（捂脸

非常感谢
